STATUS_ORDER = [ :en_cours, :validée, :annulée ]
STATUS_VENTE = [ :en_cours, :validée, :annulée ]
STATUS_ORDER_ITEM = [ :en_cours, :validé, :annulé ]
TYPE_DELIVERY = [ :collecte_magasin, :livraison_domicile ]
STATUS_DELIVERY = [ :en_attente, :préparée, :à_récolter, :envoyée, :reçue ]
